
package guru.mmp.sample.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SampleService", targetNamespace = "http://ws.sample.mmp.guru", wsdlLocation = "file:/Users/marcus/Develop/MMP/mmp-java/src/mmp-sample-client/src/main/resources/META-INF/wsdl/SampleService.wsdl")
public class SampleService
    extends Service
{

    private final static URL SAMPLESERVICE_WSDL_LOCATION;
    private final static WebServiceException SAMPLESERVICE_EXCEPTION;
    private final static QName SAMPLESERVICE_QNAME = new QName("http://ws.sample.mmp.guru", "SampleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/marcus/Develop/MMP/mmp-java/src/mmp-sample-client/src/main/resources/META-INF/wsdl/SampleService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAMPLESERVICE_WSDL_LOCATION = url;
        SAMPLESERVICE_EXCEPTION = e;
    }

    public SampleService() {
        super(__getWsdlLocation(), SAMPLESERVICE_QNAME);
    }

    public SampleService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAMPLESERVICE_QNAME, features);
    }

    public SampleService(URL wsdlLocation) {
        super(wsdlLocation, SAMPLESERVICE_QNAME);
    }

    public SampleService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAMPLESERVICE_QNAME, features);
    }

    public SampleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SampleService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISampleService
     */
    @WebEndpoint(name = "SampleService")
    public ISampleService getSampleService() {
        return super.getPort(new QName("http://ws.sample.mmp.guru", "SampleService"), ISampleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISampleService
     */
    @WebEndpoint(name = "SampleService")
    public ISampleService getSampleService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.sample.mmp.guru", "SampleService"), ISampleService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAMPLESERVICE_EXCEPTION!= null) {
            throw SAMPLESERVICE_EXCEPTION;
        }
        return SAMPLESERVICE_WSDL_LOCATION;
    }

}
