
package vim25service;

import javax.xml.ws.WebFault;
import vim25.ActiveDirectoryFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ActiveDirectoryFaultFault", targetNamespace = "urn:vim25")
public class ActiveDirectoryFaultFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ActiveDirectoryFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ActiveDirectoryFaultFaultMsg(String message, ActiveDirectoryFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ActiveDirectoryFaultFaultMsg(String message, ActiveDirectoryFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.ActiveDirectoryFault
     */
    public ActiveDirectoryFault getFaultInfo() {
        return faultInfo;
    }

}
