
package vim25service;

import javax.xml.ws.WebFault;
import vim25.CustomizationFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CustomizationFaultFault", targetNamespace = "urn:vim25")
public class CustomizationFaultFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CustomizationFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CustomizationFaultFaultMsg(String message, CustomizationFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CustomizationFaultFaultMsg(String message, CustomizationFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.CustomizationFault
     */
    public CustomizationFault getFaultInfo() {
        return faultInfo;
    }

}
