
package vim25service;

import javax.xml.ws.WebFault;
import vim25.FilterInUse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "FilterInUseFault", targetNamespace = "urn:vim25")
public class FilterInUseFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FilterInUse faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FilterInUseFaultMsg(String message, FilterInUse faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FilterInUseFaultMsg(String message, FilterInUse faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.FilterInUse
     */
    public FilterInUse getFaultInfo() {
        return faultInfo;
    }

}
