
package vim25service;

import javax.xml.ws.WebFault;
import vim25.HostPowerOpFailed;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "HostPowerOpFailedFault", targetNamespace = "urn:vim25")
public class HostPowerOpFailedFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private HostPowerOpFailed faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public HostPowerOpFailedFaultMsg(String message, HostPowerOpFailed faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public HostPowerOpFailedFaultMsg(String message, HostPowerOpFailed faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.HostPowerOpFailed
     */
    public HostPowerOpFailed getFaultInfo() {
        return faultInfo;
    }

}
