
package vim25service;

import javax.xml.ws.WebFault;
import vim25.HostConfigFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "HostConfigFaultFault", targetNamespace = "urn:vim25")
public class HostConfigFaultFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private HostConfigFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public HostConfigFaultFaultMsg(String message, HostConfigFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public HostConfigFaultFaultMsg(String message, HostConfigFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.HostConfigFault
     */
    public HostConfigFault getFaultInfo() {
        return faultInfo;
    }

}
