
package vim25service;

import javax.xml.ws.WebFault;
import vim25.InvalidLicense;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidLicenseFault", targetNamespace = "urn:vim25")
public class InvalidLicenseFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidLicense faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidLicenseFaultMsg(String message, InvalidLicense faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidLicenseFaultMsg(String message, InvalidLicense faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.InvalidLicense
     */
    public InvalidLicense getFaultInfo() {
        return faultInfo;
    }

}
