
package vim25service;

import javax.xml.ws.WebFault;
import vim25.InvalidCollectorVersion;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidCollectorVersionFault", targetNamespace = "urn:vim25")
public class InvalidCollectorVersionFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidCollectorVersion faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidCollectorVersionFaultMsg(String message, InvalidCollectorVersion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidCollectorVersionFaultMsg(String message, InvalidCollectorVersion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.InvalidCollectorVersion
     */
    public InvalidCollectorVersion getFaultInfo() {
        return faultInfo;
    }

}
