
package vim25service;

import javax.xml.ws.WebFault;
import vim25.InvalidState;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidStateFault", targetNamespace = "urn:vim25")
public class InvalidStateFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidState faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidStateFaultMsg(String message, InvalidState faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidStateFaultMsg(String message, InvalidState faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.InvalidState
     */
    public InvalidState getFaultInfo() {
        return faultInfo;
    }

}
