
package vim25service;

import javax.xml.ws.WebFault;
import vim25.InvalidDatastorePath;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidDatastorePathFault", targetNamespace = "urn:vim25")
public class InvalidDatastorePathFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidDatastorePath faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidDatastorePathFaultMsg(String message, InvalidDatastorePath faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidDatastorePathFaultMsg(String message, InvalidDatastorePath faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.InvalidDatastorePath
     */
    public InvalidDatastorePath getFaultInfo() {
        return faultInfo;
    }

}
