
package vim25service;

import javax.xml.ws.WebFault;
import vim25.InvalidLogin;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidLoginFault", targetNamespace = "urn:vim25")
public class InvalidLoginFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidLogin faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidLoginFaultMsg(String message, InvalidLogin faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidLoginFaultMsg(String message, InvalidLogin faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.InvalidLogin
     */
    public InvalidLogin getFaultInfo() {
        return faultInfo;
    }

}
