
package vim25service;

import javax.xml.ws.WebFault;
import vim25.InvalidPrivilege;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidPrivilegeFault", targetNamespace = "urn:vim25")
public class InvalidPrivilegeFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidPrivilege faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidPrivilegeFaultMsg(String message, InvalidPrivilege faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidPrivilegeFaultMsg(String message, InvalidPrivilege faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.InvalidPrivilege
     */
    public InvalidPrivilege getFaultInfo() {
        return faultInfo;
    }

}
