
package vim25service;

import javax.xml.ws.WebFault;
import vim25.InvalidName;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidNameFault", targetNamespace = "urn:vim25")
public class InvalidNameFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidName faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidNameFaultMsg(String message, InvalidName faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidNameFaultMsg(String message, InvalidName faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.InvalidName
     */
    public InvalidName getFaultInfo() {
        return faultInfo;
    }

}
