
package vim25service;

import javax.xml.ws.WebFault;
import vim25.IORMNotSupportedHostOnDatastore;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IORMNotSupportedHostOnDatastoreFault", targetNamespace = "urn:vim25")
public class IORMNotSupportedHostOnDatastoreFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IORMNotSupportedHostOnDatastore faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IORMNotSupportedHostOnDatastoreFaultMsg(String message, IORMNotSupportedHostOnDatastore faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IORMNotSupportedHostOnDatastoreFaultMsg(String message, IORMNotSupportedHostOnDatastore faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.IORMNotSupportedHostOnDatastore
     */
    public IORMNotSupportedHostOnDatastore getFaultInfo() {
        return faultInfo;
    }

}
