
package vim25service;

import javax.xml.ws.WebFault;
import vim25.IscsiFaultInvalidVnic;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IscsiFaultInvalidVnicFault", targetNamespace = "urn:vim25")
public class IscsiFaultInvalidVnicFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IscsiFaultInvalidVnic faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IscsiFaultInvalidVnicFaultMsg(String message, IscsiFaultInvalidVnic faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IscsiFaultInvalidVnicFaultMsg(String message, IscsiFaultInvalidVnic faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.IscsiFaultInvalidVnic
     */
    public IscsiFaultInvalidVnic getFaultInfo() {
        return faultInfo;
    }

}
