
package vim25service;

import javax.xml.ws.WebFault;
import vim25.IscsiFaultVnicNotBound;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IscsiFaultVnicNotBoundFault", targetNamespace = "urn:vim25")
public class IscsiFaultVnicNotBoundFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IscsiFaultVnicNotBound faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IscsiFaultVnicNotBoundFaultMsg(String message, IscsiFaultVnicNotBound faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IscsiFaultVnicNotBoundFaultMsg(String message, IscsiFaultVnicNotBound faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.IscsiFaultVnicNotBound
     */
    public IscsiFaultVnicNotBound getFaultInfo() {
        return faultInfo;
    }

}
