
package vim25service;

import javax.xml.ws.WebFault;
import vim25.MigrationFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MigrationFaultFault", targetNamespace = "urn:vim25")
public class MigrationFaultFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MigrationFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MigrationFaultFaultMsg(String message, MigrationFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MigrationFaultFaultMsg(String message, MigrationFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.MigrationFault
     */
    public MigrationFault getFaultInfo() {
        return faultInfo;
    }

}
