
package vim25service;

import javax.xml.ws.WebFault;
import vim25.PatchMetadataInvalid;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PatchMetadataInvalidFault", targetNamespace = "urn:vim25")
public class PatchMetadataInvalidFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PatchMetadataInvalid faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PatchMetadataInvalidFaultMsg(String message, PatchMetadataInvalid faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PatchMetadataInvalidFaultMsg(String message, PatchMetadataInvalid faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.PatchMetadataInvalid
     */
    public PatchMetadataInvalid getFaultInfo() {
        return faultInfo;
    }

}
