
package vim25service;

import javax.xml.ws.WebFault;
import vim25.ProfileUpdateFailed;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ProfileUpdateFailedFault", targetNamespace = "urn:vim25")
public class ProfileUpdateFailedFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ProfileUpdateFailed faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ProfileUpdateFailedFaultMsg(String message, ProfileUpdateFailed faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ProfileUpdateFailedFaultMsg(String message, ProfileUpdateFailed faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.ProfileUpdateFailed
     */
    public ProfileUpdateFailed getFaultInfo() {
        return faultInfo;
    }

}
