
package vim25service;

import javax.xml.ws.WebFault;
import vim25.RemoveFailed;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RemoveFailedFault", targetNamespace = "urn:vim25")
public class RemoveFailedFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RemoveFailed faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public RemoveFailedFaultMsg(String message, RemoveFailed faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public RemoveFailedFaultMsg(String message, RemoveFailed faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.RemoveFailed
     */
    public RemoveFailed getFaultInfo() {
        return faultInfo;
    }

}
