
package vim25service;

import javax.xml.ws.WebFault;
import vim25.ResourceInUse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ResourceInUseFault", targetNamespace = "urn:vim25")
public class ResourceInUseFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ResourceInUse faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ResourceInUseFaultMsg(String message, ResourceInUse faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ResourceInUseFaultMsg(String message, ResourceInUse faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.ResourceInUse
     */
    public ResourceInUse getFaultInfo() {
        return faultInfo;
    }

}
