
package vim25service;

import javax.xml.ws.WebFault;
import vim25.TaskInProgress;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "TaskInProgressFault", targetNamespace = "urn:vim25")
public class TaskInProgressFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TaskInProgress faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TaskInProgressFaultMsg(String message, TaskInProgress faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TaskInProgressFaultMsg(String message, TaskInProgress faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.TaskInProgress
     */
    public TaskInProgress getFaultInfo() {
        return faultInfo;
    }

}
