
package vim25service;

import javax.xml.ws.WebFault;
import vim25.Timedout;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "TimedoutFault", targetNamespace = "urn:vim25")
public class TimedoutFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Timedout faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TimedoutFaultMsg(String message, Timedout faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TimedoutFaultMsg(String message, Timedout faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.Timedout
     */
    public Timedout getFaultInfo() {
        return faultInfo;
    }

}
