
package vim25service;

import javax.xml.ws.WebFault;
import vim25.UserNotFound;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UserNotFoundFault", targetNamespace = "urn:vim25")
public class UserNotFoundFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UserNotFound faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UserNotFoundFaultMsg(String message, UserNotFound faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UserNotFoundFaultMsg(String message, UserNotFound faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.UserNotFound
     */
    public UserNotFound getFaultInfo() {
        return faultInfo;
    }

}
