
package vim25service;

import javax.xml.ws.WebFault;
import vim25.VmfsAmbiguousMount;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "VmfsAmbiguousMountFault", targetNamespace = "urn:vim25")
public class VmfsAmbiguousMountFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private VmfsAmbiguousMount faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public VmfsAmbiguousMountFaultMsg(String message, VmfsAmbiguousMount faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public VmfsAmbiguousMountFaultMsg(String message, VmfsAmbiguousMount faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.VmfsAmbiguousMount
     */
    public VmfsAmbiguousMount getFaultInfo() {
        return faultInfo;
    }

}
