
package vim25service;

import javax.xml.ws.WebFault;
import vim25.VsanFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "VsanFaultFault", targetNamespace = "urn:vim25")
public class VsanFaultFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private VsanFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public VsanFaultFaultMsg(String message, VsanFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public VsanFaultFaultMsg(String message, VsanFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vim25.VsanFault
     */
    public VsanFault getFaultInfo() {
        return faultInfo;
    }

}
