application:
  databaseold:
    dataSource: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:mem:application;MODE=DB2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    minPoolSize: 5
    maxPoolSize: 10

  database:
    dataSource: com.microsoft.sqlserver.jdbc.SQLServerXADataSource
    url: jdbc:sqlserver://192.168.185.130:1433;databaseName=Samples;user=sa;password=Password1
    minPoolSize: 5
    maxPoolSize: 10

---
spring:
    profiles: development
application:
  key: development_value
---
spring:
    profiles: production
application:
  key: production_value
