application:

  database:
    dataSource: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:mem:application;MODE=DB2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    minPoolSize: 5
    maxPoolSize: 10

  database-sql-server:
    dataSource: com.microsoft.sqlserver.jdbc.SQLServerXADataSource
    url: jdbc:sqlserver://192.168.185.130:1433;databaseName=Sample;user=Sample;password=Password1
    minPoolSize: 5
    maxPoolSize: 10

  mutualSSL:
    enabled: true
    keyStore:
      type: JKS
      path: classpath:META-INF/localhost.jks
      alias: localhost
      password: Password1
    trustStore:
      type: JKS
      path: classpath:META-INF/localhost.jks
      password: Password1
---
spring:
    profiles: development
---
spring:
    profiles: production
