
package guru.mmp.service.sample;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISampleService", targetNamespace = "http://sample.service.mmp.guru")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISampleService {


    /**
     * 
     * @return
     *     returns guru.mmp.service.sample.Data
     * @throws SampleServiceException
     */
    @WebMethod(operationName = "GetData")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetData", targetNamespace = "http://sample.service.mmp.guru", className = "guru.mmp.service.sample.GetData")
    @ResponseWrapper(localName = "GetDataResponse", targetNamespace = "http://sample.service.mmp.guru", className = "guru.mmp.service.sample.GetDataResponse")
    public Data getData()
        throws SampleServiceException
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVersion")
    @WebResult(name = "Version", targetNamespace = "")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "http://sample.service.mmp.guru", className = "guru.mmp.service.sample.GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "http://sample.service.mmp.guru", className = "guru.mmp.service.sample.GetVersionResponse")
    public String getVersion();

    /**
     * 
     * @throws SampleServiceException
     */
    @WebMethod(operationName = "TestExceptionHandling")
    @RequestWrapper(localName = "TestExceptionHandling", targetNamespace = "http://sample.service.mmp.guru", className = "guru.mmp.service.sample.TestExceptionHandling")
    @ResponseWrapper(localName = "TestExceptionHandlingResponse", targetNamespace = "http://sample.service.mmp.guru", className = "guru.mmp.service.sample.TestExceptionHandlingResponse")
    public void testExceptionHandling()
        throws SampleServiceException
    ;

}
