
package guru.mmp.service.sample;

import javax.xml.ws.WebFault;
import guru.mmp.model.application.ServiceError;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SampleServiceException", targetNamespace = "http://sample.service.mmp.guru")
public class SampleServiceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServiceError faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SampleServiceException(String message, ServiceError faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SampleServiceException(String message, ServiceError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: guru.mmp.model.application.ServiceError
     */
    public ServiceError getFaultInfo() {
        return faultInfo;
    }

}
