package guru.mmp.service.sample;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-02T20:51:23.745+02:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "SampleService", 
                  wsdlLocation = "file:/Volumes/Data/Develop/MMP/mmp-java/src/mmp-sample-client/src/main/resources/META-INF/wsdl/SampleService.wsdl",
                  targetNamespace = "http://sample.service.mmp.guru") 
public class SampleService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sample.service.mmp.guru", "SampleService");
    public final static QName ISampleServicePort = new QName("http://sample.service.mmp.guru", "ISampleServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Volumes/Data/Develop/MMP/mmp-java/src/mmp-sample-client/src/main/resources/META-INF/wsdl/SampleService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SampleService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Volumes/Data/Develop/MMP/mmp-java/src/mmp-sample-client/src/main/resources/META-INF/wsdl/SampleService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SampleService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SampleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SampleService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SampleService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SampleService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SampleService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ISampleService
     */
    @WebEndpoint(name = "ISampleServicePort")
    public ISampleService getISampleServicePort() {
        return super.getPort(ISampleServicePort, ISampleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISampleService
     */
    @WebEndpoint(name = "ISampleServicePort")
    public ISampleService getISampleServicePort(WebServiceFeature... features) {
        return super.getPort(ISampleServicePort, ISampleService.class, features);
    }

}
