
package com.mymobileapi.api5;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "API", targetNamespace = "http://www.mymobileapi.com/api5", wsdlLocation = "file:/Volumes/Data/Develop/MMP/mmp-java/src/mmp-application-sms/src/main/resources/META-INF/wsdl/MyMobileAPI.wsdl")
public class API
    extends Service
{

    private final static URL API_WSDL_LOCATION;
    private final static WebServiceException API_EXCEPTION;
    private final static QName API_QNAME = new QName("http://www.mymobileapi.com/api5", "API");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Volumes/Data/Develop/MMP/mmp-java/src/mmp-application-sms/src/main/resources/META-INF/wsdl/MyMobileAPI.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        API_WSDL_LOCATION = url;
        API_EXCEPTION = e;
    }

    public API() {
        super(__getWsdlLocation(), API_QNAME);
    }

    public API(WebServiceFeature... features) {
        super(__getWsdlLocation(), API_QNAME, features);
    }

    public API(URL wsdlLocation) {
        super(wsdlLocation, API_QNAME);
    }

    public API(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, API_QNAME, features);
    }

    public API(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public API(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns APISoap
     */
    @WebEndpoint(name = "APISoap")
    public APISoap getAPISoap() {
        return super.getPort(new QName("http://www.mymobileapi.com/api5", "APISoap"), APISoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns APISoap
     */
    @WebEndpoint(name = "APISoap")
    public APISoap getAPISoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.mymobileapi.com/api5", "APISoap"), APISoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (API_EXCEPTION!= null) {
            throw API_EXCEPTION;
        }
        return API_WSDL_LOCATION;
    }

}
