package com.mymobileapi.api5;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 */
@WebService(name = "APISoap", targetNamespace = "http://www.mymobileapi.com/api5")
@XmlSeeAlso({ObjectFactory.class})
public interface APISoap
{

  /**
   * @param password
   * @param username
   *
   * @return returns com.mymobileapi.api5.CreditsDSResponse.CreditsDSResult
   */
  @WebMethod(operationName = "Credits_DS", action = "http://www.mymobileapi.com/api5/Credits_DS")
  @WebResult(name = "Credits_DSResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Credits_DS", targetNamespace = "http://www.mymobileapi.com/api5",
    className = "com.mymobileapi.api5.CreditsDS")
  @ResponseWrapper(localName = "Credits_DSResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.CreditsDSResponse")
  public com.mymobileapi.api5.CreditsDSResponse.CreditsDSResult creditsDS(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password);

  /**
   * @param password
   * @param username
   *
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "Credits_STR", action = "http://www.mymobileapi.com/api5/Credits_STR")
  @WebResult(name = "Credits_STRResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Credits_STR", targetNamespace = "http://www.mymobileapi.com/api5",
    className = "com.mymobileapi.api5.CreditsSTR")
  @ResponseWrapper(localName = "Credits_STRResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.CreditsSTRResponse")
  public String creditsSTR(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns byte[]
   */
  @WebMethod(operationName = "Doc_DS_ZIP", action = "http://www.mymobileapi.com/api5/Doc_DS_ZIP")
  @WebResult(name = "Doc_DS_ZIPResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Doc_DS_ZIP", targetNamespace = "http://www.mymobileapi.com/api5",
    className = "com.mymobileapi.api5.DocDSZIP")
  @ResponseWrapper(localName = "Doc_DS_ZIPResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.DocDSZIPResponse")
  public byte[] docDSZIP(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.DocDSZIP.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns com.mymobileapi.api5.GroupsListDSDSResponse.GroupsListDSDSResult
   */
  @WebMethod(operationName = "Groups_List_DS_DS", action = "http://www.mymobileapi" +
    ".com/api5/Groups_List_DS_DS")
  @WebResult(name = "Groups_List_DS_DSResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Groups_List_DS_DS", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.GroupsListDSDS")
  @ResponseWrapper(localName = "Groups_List_DS_DSResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.GroupsListDSDSResponse")
  public com.mymobileapi.api5.GroupsListDSDSResponse.GroupsListDSDSResult groupsListDSDS(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.GroupsListDSDS.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "Groups_List_DS_STR", action = "http://www.mymobileapi" +
    ".com/api5/Groups_List_DS_STR")
  @WebResult(name = "Groups_List_DS_STRResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Groups_List_DS_STR", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.GroupsListDSSTR")
  @ResponseWrapper(localName = "Groups_List_DS_STRResponse", targetNamespace = "http://www" + "" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.GroupsListDSSTRResponse")
  public String groupsListDSSTR(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.GroupsListDSSTR.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns com.mymobileapi.api5.GroupsListSTRDSResponse.GroupsListSTRDSResult
   */
  @WebMethod(operationName = "Groups_List_STR_DS", action = "http://www.mymobileapi" +
    ".com/api5/Groups_List_STR_DS")
  @WebResult(name = "Groups_List_STR_DSResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Groups_List_STR_DS", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.GroupsListSTRDS")
  @ResponseWrapper(localName = "Groups_List_STR_DSResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.GroupsListSTRDSResponse")
  public com.mymobileapi.api5.GroupsListSTRDSResponse.GroupsListSTRDSResult groupsListSTRDS(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "Groups_List_STR_STR", action = "http://www.mymobileapi" +
    ".com/api5/Groups_List_STR_STR")
  @WebResult(name = "Groups_List_STR_STRResult", targetNamespace = "http://www.mymobileapi" +
    ".com/api5")
  @RequestWrapper(localName = "Groups_List_STR_STR", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.GroupsListSTRSTR")
  @ResponseWrapper(localName = "Groups_List_STR_STRResponse", targetNamespace = "http://www" + "" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.GroupsListSTRSTRResponse")
  public String groupsListSTRSTR(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns com.mymobileapi.api5.ReplyDSDSResponse.ReplyDSDSResult
   */
  @WebMethod(operationName = "Reply_DS_DS", action = "http://www.mymobileapi.com/api5/Reply_DS_DS")
  @WebResult(name = "Reply_DS_DSResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Reply_DS_DS", targetNamespace = "http://www.mymobileapi.com/api5",
    className = "com.mymobileapi.api5.ReplyDSDS")
  @ResponseWrapper(localName = "Reply_DS_DSResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ReplyDSDSResponse")
  public com.mymobileapi.api5.ReplyDSDSResponse.ReplyDSDSResult replyDSDS(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.ReplyDSDS.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "Reply_DS_STR", action = "http://www.mymobileapi" +
    ".com/api5/Reply_DS_STR")
  @WebResult(name = "Reply_DS_STRResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Reply_DS_STR", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ReplyDSSTR")
  @ResponseWrapper(localName = "Reply_DS_STRResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ReplyDSSTRResponse")
  public String replyDSSTR(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.ReplyDSSTR.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns byte[]
   */
  @WebMethod(operationName = "Reply_DS_ZIP", action = "http://www.mymobileapi" +
    ".com/api5/Reply_DS_ZIP")
  @WebResult(name = "Reply_DS_ZIPResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Reply_DS_ZIP", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ReplyDSZIP")
  @ResponseWrapper(localName = "Reply_DS_ZIPResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ReplyDSZIPResponse")
  public byte[] replyDSZIP(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.ReplyDSZIP.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns com.mymobileapi.api5.ReplySTRDSResponse.ReplySTRDSResult
   */
  @WebMethod(operationName = "Reply_STR_DS", action = "http://www.mymobileapi" +
    ".com/api5/Reply_STR_DS")
  @WebResult(name = "Reply_STR_DSResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Reply_STR_DS", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ReplySTRDS")
  @ResponseWrapper(localName = "Reply_STR_DSResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ReplySTRDSResponse")
  public com.mymobileapi.api5.ReplySTRDSResponse.ReplySTRDSResult replySTRDS(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "Reply_STR_STR", action = "http://www.mymobileapi" +
    ".com/api5/Reply_STR_STR")
  @WebResult(name = "Reply_STR_STRResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Reply_STR_STR", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ReplySTRSTR")
  @ResponseWrapper(localName = "Reply_STR_STRResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ReplySTRSTRResponse")
  public String replySTRSTR(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns byte[]
   */
  @WebMethod(operationName = "Reply_STR_ZIP", action = "http://www.mymobileapi" +
    ".com/api5/Reply_STR_ZIP")
  @WebResult(name = "Reply_STR_ZIPResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Reply_STR_ZIP", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ReplySTRZIP")
  @ResponseWrapper(localName = "Reply_STR_ZIPResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ReplySTRZIPResponse")
  public byte[] replySTRZIP(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns com.mymobileapi.api5.SendDSDSResponse.SendDSDSResult
   */
  @WebMethod(operationName = "Send_DS_DS", action = "http://www.mymobileapi.com/api5/Send_DS_DS")
  @WebResult(name = "Send_DS_DSResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Send_DS_DS", targetNamespace = "http://www.mymobileapi.com/api5",
    className = "com.mymobileapi.api5.SendDSDS")
  @ResponseWrapper(localName = "Send_DS_DSResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.SendDSDSResponse")
  public com.mymobileapi.api5.SendDSDSResponse.SendDSDSResult sendDSDS(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.SendDSDS.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "Send_DS_STR", action = "http://www.mymobileapi.com/api5/Send_DS_STR")
  @WebResult(name = "Send_DS_STRResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Send_DS_STR", targetNamespace = "http://www.mymobileapi.com/api5",
    className = "com.mymobileapi.api5.SendDSSTR")
  @ResponseWrapper(localName = "Send_DS_STRResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.SendDSSTRResponse")
  public String sendDSSTR(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.SendDSSTR.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns com.mymobileapi.api5.SendSTRDSResponse.SendSTRDSResult
   */
  @WebMethod(operationName = "Send_STR_DS", action = "http://www.mymobileapi.com/api5/Send_STR_DS")
  @WebResult(name = "Send_STR_DSResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Send_STR_DS", targetNamespace = "http://www.mymobileapi.com/api5",
    className = "com.mymobileapi.api5.SendSTRDS")
  @ResponseWrapper(localName = "Send_STR_DSResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.SendSTRDSResponse")
  public com.mymobileapi.api5.SendSTRDSResponse.SendSTRDSResult sendSTRDS(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "Send_STR_STR", action = "http://www.mymobileapi" +
    ".com/api5/Send_STR_STR")
  @WebResult(name = "Send_STR_STRResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Send_STR_STR", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.SendSTRSTR")
  @ResponseWrapper(localName = "Send_STR_STRResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.SendSTRSTRResponse")
  public String sendSTRSTR(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns byte[]
   */
  @WebMethod(operationName = "Send_ZIP_ZIP", action = "http://www.mymobileapi" +
    ".com/api5/Send_ZIP_ZIP")
  @WebResult(name = "Send_ZIP_ZIPResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Send_ZIP_ZIP", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.SendZIPZIP")
  @ResponseWrapper(localName = "Send_ZIP_ZIPResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.SendZIPZIPResponse")
  public byte[] sendZIPZIP(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") byte[] data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns com.mymobileapi.api5.SentDSDSResponse.SentDSDSResult
   */
  @WebMethod(operationName = "Sent_DS_DS", action = "http://www.mymobileapi.com/api5/Sent_DS_DS")
  @WebResult(name = "Sent_DS_DSResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Sent_DS_DS", targetNamespace = "http://www.mymobileapi.com/api5",
    className = "com.mymobileapi.api5.SentDSDS")
  @ResponseWrapper(localName = "Sent_DS_DSResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.SentDSDSResponse")
  public com.mymobileapi.api5.SentDSDSResponse.SentDSDSResult sentDSDS(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.SentDSDS.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "Sent_DS_STR", action = "http://www.mymobileapi.com/api5/Sent_DS_STR")
  @WebResult(name = "Sent_DS_STRResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Sent_DS_STR", targetNamespace = "http://www.mymobileapi.com/api5",
    className = "com.mymobileapi.api5.SentDSSTR")
  @ResponseWrapper(localName = "Sent_DS_STRResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.SentDSSTRResponse")
  public String sentDSSTR(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.SentDSSTR.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns byte[]
   */
  @WebMethod(operationName = "Sent_DS_ZIP", action = "http://www.mymobileapi.com/api5/Sent_DS_ZIP")
  @WebResult(name = "Sent_DS_ZIPResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Sent_DS_ZIP", targetNamespace = "http://www.mymobileapi.com/api5",
    className = "com.mymobileapi.api5.SentDSZIP")
  @ResponseWrapper(localName = "Sent_DS_ZIPResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.SentDSZIPResponse")
  public byte[] sentDSZIP(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.SentDSZIP.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns com.mymobileapi.api5.SentSTRDSResponse.SentSTRDSResult
   */
  @WebMethod(operationName = "Sent_STR_DS", action = "http://www.mymobileapi.com/api5/Sent_STR_DS")
  @WebResult(name = "Sent_STR_DSResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Sent_STR_DS", targetNamespace = "http://www.mymobileapi.com/api5",
    className = "com.mymobileapi.api5.SentSTRDS")
  @ResponseWrapper(localName = "Sent_STR_DSResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.SentSTRDSResponse")
  public com.mymobileapi.api5.SentSTRDSResponse.SentSTRDSResult sentSTRDS(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "Sent_STR_STR", action = "http://www.mymobileapi" +
    ".com/api5/Sent_STR_STR")
  @WebResult(name = "Sent_STR_STRResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Sent_STR_STR", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.SentSTRSTR")
  @ResponseWrapper(localName = "Sent_STR_STRResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.SentSTRSTRResponse")
  public String sentSTRSTR(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns byte[]
   */
  @WebMethod(operationName = "Sent_STR_ZIP", action = "http://www.mymobileapi" +
    ".com/api5/Sent_STR_ZIP")
  @WebResult(name = "Sent_STR_ZIPResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "Sent_STR_ZIP", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.SentSTRZIP")
  @ResponseWrapper(localName = "Sent_STR_ZIPResponse", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.SentSTRZIPResponse")
  public byte[] sentSTRZIP(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns com.mymobileapi.api5.ShortCodeCountDSDSResponse.ShortCodeCountDSDSResult
   */
  @WebMethod(operationName = "ShortCode_Count_DS_DS", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_Count_DS_DS")
  @WebResult(name = "ShortCode_Count_DS_DSResult", targetNamespace = "http://www.mymobileapi" +
    ".com/api5")
  @RequestWrapper(localName = "ShortCode_Count_DS_DS", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ShortCodeCountDSDS")
  @ResponseWrapper(localName = "ShortCode_Count_DS_DSResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeCountDSDSResponse")
  public com.mymobileapi.api5.ShortCodeCountDSDSResponse.ShortCodeCountDSDSResult
  shortCodeCountDSDS(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.ShortCodeCountDSDS.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "ShortCode_Count_DS_STR", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_Count_DS_STR")
  @WebResult(name = "ShortCode_Count_DS_STRResult", targetNamespace = "http://www.mymobileapi" +
    ".com/api5")
  @RequestWrapper(localName = "ShortCode_Count_DS_STR", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ShortCodeCountDSSTR")
  @ResponseWrapper(localName = "ShortCode_Count_DS_STRResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeCountDSSTRResponse")
  public String shortCodeCountDSSTR(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.ShortCodeCountDSSTR.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns com.mymobileapi.api5.ShortCodeCountSTRDSResponse.ShortCodeCountSTRDSResult
   */
  @WebMethod(operationName = "ShortCode_Count_STR_DS", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_Count_STR_DS")
  @WebResult(name = "ShortCode_Count_STR_DSResult", targetNamespace = "http://www.mymobileapi" +
    ".com/api5")
  @RequestWrapper(localName = "ShortCode_Count_STR_DS", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ShortCodeCountSTRDS")
  @ResponseWrapper(localName = "ShortCode_Count_STR_DSResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeCountSTRDSResponse")
  public com.mymobileapi.api5.ShortCodeCountSTRDSResponse.ShortCodeCountSTRDSResult
  shortCodeCountSTRDS(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "ShortCode_Count_STR_STR", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_Count_STR_STR")
  @WebResult(name = "ShortCode_Count_STR_STRResult", targetNamespace = "http://www.mymobileapi" +
    ".com/api5")
  @RequestWrapper(localName = "ShortCode_Count_STR_STR", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeCountSTRSTR")
  @ResponseWrapper(localName = "ShortCode_Count_STR_STRResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeCountSTRSTRResponse")
  public String shortCodeCountSTRSTR(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns com.mymobileapi.api5.ShortCodeDSDSResponse.ShortCodeDSDSResult
   */
  @WebMethod(operationName = "ShortCode_DS_DS", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_DS_DS")
  @WebResult(name = "ShortCode_DS_DSResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "ShortCode_DS_DS", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ShortCodeDSDS")
  @ResponseWrapper(localName = "ShortCode_DS_DSResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeDSDSResponse")
  public com.mymobileapi.api5.ShortCodeDSDSResponse.ShortCodeDSDSResult shortCodeDSDS(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.ShortCodeDSDS.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "ShortCode_DS_STR", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_DS_STR")
  @WebResult(name = "ShortCode_DS_STRResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "ShortCode_DS_STR", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ShortCodeDSSTR")
  @ResponseWrapper(localName = "ShortCode_DS_STRResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeDSSTRResponse")
  public String shortCodeDSSTR(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.ShortCodeDSSTR.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns com.mymobileapi.api5.ShortCodeGetDSDSResponse.ShortCodeGetDSDSResult
   */
  @WebMethod(operationName = "ShortCode_Get_DS_DS", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_Get_DS_DS")
  @WebResult(name = "ShortCode_Get_DS_DSResult", targetNamespace = "http://www.mymobileapi" +
    ".com/api5")
  @RequestWrapper(localName = "ShortCode_Get_DS_DS", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ShortCodeGetDSDS")
  @ResponseWrapper(localName = "ShortCode_Get_DS_DSResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeGetDSDSResponse")
  public com.mymobileapi.api5.ShortCodeGetDSDSResponse.ShortCodeGetDSDSResult shortCodeGetDSDS(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.ShortCodeGetDSDS.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "ShortCode_Get_DS_STR", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_Get_DS_STR")
  @WebResult(name = "ShortCode_Get_DS_STRResult", targetNamespace = "http://www.mymobileapi" +
    ".com/api5")
  @RequestWrapper(localName = "ShortCode_Get_DS_STR", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ShortCodeGetDSSTR")
  @ResponseWrapper(localName = "ShortCode_Get_DS_STRResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeGetDSSTRResponse")
  public String shortCodeGetDSSTR(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.ShortCodeGetDSSTR.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns byte[]
   */
  @WebMethod(operationName = "ShortCode_Get_DS_ZIP", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_Get_DS_ZIP")
  @WebResult(name = "ShortCode_Get_DS_ZIPResult", targetNamespace = "http://www.mymobileapi" +
    ".com/api5")
  @RequestWrapper(localName = "ShortCode_Get_DS_ZIP", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ShortCodeGetDSZIP")
  @ResponseWrapper(localName = "ShortCode_Get_DS_ZIPResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeGetDSZIPResponse")
  public byte[] shortCodeGetDSZIP(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.ShortCodeGetDSZIP.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns com.mymobileapi.api5.ShortCodeGetSTRDSResponse.ShortCodeGetSTRDSResult
   */
  @WebMethod(operationName = "ShortCode_Get_STR_DS", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_Get_STR_DS")
  @WebResult(name = "ShortCode_Get_STR_DSResult", targetNamespace = "http://www.mymobileapi" +
    ".com/api5")
  @RequestWrapper(localName = "ShortCode_Get_STR_DS", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ShortCodeGetSTRDS")
  @ResponseWrapper(localName = "ShortCode_Get_STR_DSResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeGetSTRDSResponse")
  public com.mymobileapi.api5.ShortCodeGetSTRDSResponse.ShortCodeGetSTRDSResult shortCodeGetSTRDS(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "ShortCode_Get_STR_STR", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_Get_STR_STR")
  @WebResult(name = "ShortCode_Get_STR_STRResult", targetNamespace = "http://www.mymobileapi" +
    ".com/api5")
  @RequestWrapper(localName = "ShortCode_Get_STR_STR", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ShortCodeGetSTRSTR")
  @ResponseWrapper(localName = "ShortCode_Get_STR_STRResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeGetSTRSTRResponse")
  public String shortCodeGetSTRSTR(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns byte[]
   */
  @WebMethod(operationName = "ShortCode_Get_STR_ZIP", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_Get_STR_ZIP")
  @WebResult(name = "ShortCode_Get_STR_ZIPResult", targetNamespace = "http://www.mymobileapi" +
    ".com/api5")
  @RequestWrapper(localName = "ShortCode_Get_STR_ZIP", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ShortCodeGetSTRZIP")
  @ResponseWrapper(localName = "ShortCode_Get_STR_ZIPResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeGetSTRZIPResponse")
  public byte[] shortCodeGetSTRZIP(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns com.mymobileapi.api5.ShortCodeSTRDSResponse.ShortCodeSTRDSResult
   */
  @WebMethod(operationName = "ShortCode_STR_DS", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_STR_DS")
  @WebResult(name = "ShortCode_STR_DSResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "ShortCode_STR_DS", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ShortCodeSTRDS")
  @ResponseWrapper(localName = "ShortCode_STR_DSResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeSTRDSResponse")
  public com.mymobileapi.api5.ShortCodeSTRDSResponse.ShortCodeSTRDSResult shortCodeSTRDS(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "ShortCode_STR_STR", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_STR_STR")
  @WebResult(name = "ShortCode_STR_STRResult", targetNamespace = "http://www.mymobileapi.com/api5")
  @RequestWrapper(localName = "ShortCode_STR_STR", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ShortCodeSTRSTR")
  @ResponseWrapper(localName = "ShortCode_STR_STRResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeSTRSTRResponse")
  public String shortCodeSTRSTR(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns com.mymobileapi.api5.ShortCodeUpdateDSDSResponse.ShortCodeUpdateDSDSResult
   */
  @WebMethod(operationName = "ShortCode_Update_DS_DS", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_Update_DS_DS")
  @WebResult(name = "ShortCode_Update_DS_DSResult", targetNamespace = "http://www.mymobileapi" +
    ".com/api5")
  @RequestWrapper(localName = "ShortCode_Update_DS_DS", targetNamespace = "http://www.mymobileapi" +
    ".com/api5", className = "com.mymobileapi.api5.ShortCodeUpdateDSDS")
  @ResponseWrapper(localName = "ShortCode_Update_DS_DSResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeUpdateDSDSResponse")
  public com.mymobileapi.api5.ShortCodeUpdateDSDSResponse.ShortCodeUpdateDSDSResult
  shortCodeUpdateDSDS(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.ShortCodeUpdateDSDS.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "ShortCode_Update_DS_STR", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_Update_DS_STR")
  @WebResult(name = "ShortCode_Update_DS_STRResult", targetNamespace = "http://www.mymobileapi" +
    ".com/api5")
  @RequestWrapper(localName = "ShortCode_Update_DS_STR", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeUpdateDSSTR")
  @ResponseWrapper(localName = "ShortCode_Update_DS_STRResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeUpdateDSSTRResponse")
  public String shortCodeUpdateDSSTR(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") com.mymobileapi
      .api5.ShortCodeUpdateDSSTR.Data data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns com.mymobileapi.api5.ShortCodeUpdateSTRDSResponse.ShortCodeUpdateSTRDSResult
   */
  @WebMethod(operationName = "ShortCode_Update_STR_DS", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_Update_STR_DS")
  @WebResult(name = "ShortCode_Update_STR_DSResult", targetNamespace = "http://www.mymobileapi" +
    ".com/api5")
  @RequestWrapper(localName = "ShortCode_Update_STR_DS", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeUpdateSTRDS")
  @ResponseWrapper(localName = "ShortCode_Update_STR_DSResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeUpdateSTRDSResponse")
  public com.mymobileapi.api5.ShortCodeUpdateSTRDSResponse.ShortCodeUpdateSTRDSResult
  shortCodeUpdateSTRDS(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);

  /**
   * @param password
   * @param data
   * @param username
   *
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "ShortCode_Update_STR_STR", action = "http://www.mymobileapi" +
    ".com/api5/ShortCode_Update_STR_STR")
  @WebResult(name = "ShortCode_Update_STR_STRResult", targetNamespace = "http://www.mymobileapi" +
    ".com/api5")
  @RequestWrapper(localName = "ShortCode_Update_STR_STR", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeUpdateSTRSTR")
  @ResponseWrapper(localName = "ShortCode_Update_STR_STRResponse", targetNamespace = "http://www" +
    ".mymobileapi.com/api5", className = "com.mymobileapi.api5.ShortCodeUpdateSTRSTRResponse")
  public String shortCodeUpdateSTRSTR(
    @WebParam(name = "Username", targetNamespace = "http://www.mymobileapi.com/api5") String
      username,
    @WebParam(name = "Password", targetNamespace = "http://www.mymobileapi.com/api5") String
      password,
    @WebParam(name = "Data", targetNamespace = "http://www.mymobileapi.com/api5") String data);
}
