
package com.microsoft.schemas.sharepoint.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ListsSoap", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ListsSoap {


    /**
     * 
     * @param listName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetListResponse.GetListResult
     */
    @WebMethod(operationName = "GetList", action = "http://schemas.microsoft.com/sharepoint/soap/GetList")
    @WebResult(name = "GetListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetList")
    @ResponseWrapper(localName = "GetListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListResponse")
    public com.microsoft.schemas.sharepoint.soap.GetListResponse.GetListResult getList(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName);

    /**
     * 
     * @param viewName
     * @param listName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetListAndViewResponse.GetListAndViewResult
     */
    @WebMethod(operationName = "GetListAndView", action = "http://schemas.microsoft.com/sharepoint/soap/GetListAndView")
    @WebResult(name = "GetListAndViewResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListAndView", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListAndView")
    @ResponseWrapper(localName = "GetListAndViewResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListAndViewResponse")
    public com.microsoft.schemas.sharepoint.soap.GetListAndViewResponse.GetListAndViewResult getListAndView(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "viewName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String viewName);

    /**
     * 
     * @param listName
     */
    @WebMethod(operationName = "DeleteList", action = "http://schemas.microsoft.com/sharepoint/soap/DeleteList")
    @RequestWrapper(localName = "DeleteList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.DeleteList")
    @ResponseWrapper(localName = "DeleteListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.DeleteListResponse")
    public void deleteList(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName);

    /**
     * 
     * @param description
     * @param listName
     * @param templateID
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.AddListResponse.AddListResult
     */
    @WebMethod(operationName = "AddList", action = "http://schemas.microsoft.com/sharepoint/soap/AddList")
    @WebResult(name = "AddListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "AddList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.AddList")
    @ResponseWrapper(localName = "AddListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.AddListResponse")
    public com.microsoft.schemas.sharepoint.soap.AddListResponse.AddListResult addList(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "description", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String description,
        @WebParam(name = "templateID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        int templateID);

    /**
     * 
     * @param description
     * @param listName
     * @param templateID
     * @param featureID
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.AddListFromFeatureResponse.AddListFromFeatureResult
     */
    @WebMethod(operationName = "AddListFromFeature", action = "http://schemas.microsoft.com/sharepoint/soap/AddListFromFeature")
    @WebResult(name = "AddListFromFeatureResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "AddListFromFeature", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.AddListFromFeature")
    @ResponseWrapper(localName = "AddListFromFeatureResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.AddListFromFeatureResponse")
    public com.microsoft.schemas.sharepoint.soap.AddListFromFeatureResponse.AddListFromFeatureResult addListFromFeature(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "description", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String description,
        @WebParam(name = "featureID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String featureID,
        @WebParam(name = "templateID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        int templateID);

    /**
     * 
     * @param listVersion
     * @param deleteFields
     * @param newFields
     * @param updateFields
     * @param listName
     * @param listProperties
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.UpdateListResponse.UpdateListResult
     */
    @WebMethod(operationName = "UpdateList", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateList")
    @WebResult(name = "UpdateListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UpdateList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.UpdateList")
    @ResponseWrapper(localName = "UpdateListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.UpdateListResponse")
    public com.microsoft.schemas.sharepoint.soap.UpdateListResponse.UpdateListResult updateList(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "listProperties", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.UpdateList.ListProperties listProperties,
        @WebParam(name = "newFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.UpdateList.NewFields newFields,
        @WebParam(name = "updateFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.UpdateList.UpdateFields updateFields,
        @WebParam(name = "deleteFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.UpdateList.DeleteFields deleteFields,
        @WebParam(name = "listVersion", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listVersion);

    /**
     * 
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetListCollectionResponse.GetListCollectionResult
     */
    @WebMethod(operationName = "GetListCollection", action = "http://schemas.microsoft.com/sharepoint/soap/GetListCollection")
    @WebResult(name = "GetListCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListCollection")
    @ResponseWrapper(localName = "GetListCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListCollectionResponse")
    public com.microsoft.schemas.sharepoint.soap.GetListCollectionResponse.GetListCollectionResult getListCollection();

    /**
     * 
     * @param webID
     * @param viewName
     * @param queryOptions
     * @param query
     * @param listName
     * @param rowLimit
     * @param viewFields
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetListItemsResponse.GetListItemsResult
     */
    @WebMethod(operationName = "GetListItems", action = "http://schemas.microsoft.com/sharepoint/soap/GetListItems")
    @WebResult(name = "GetListItemsResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListItems", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListItems")
    @ResponseWrapper(localName = "GetListItemsResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListItemsResponse")
    public com.microsoft.schemas.sharepoint.soap.GetListItemsResponse.GetListItemsResult getListItems(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "viewName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String viewName,
        @WebParam(name = "query", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.GetListItems.Query query,
        @WebParam(name = "viewFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.GetListItems.ViewFields viewFields,
        @WebParam(name = "rowLimit", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String rowLimit,
        @WebParam(name = "queryOptions", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.GetListItems.QueryOptions queryOptions,
        @WebParam(name = "webID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String webID);

    /**
     * 
     * @param contains
     * @param listName
     * @param viewFields
     * @param since
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetListItemChangesResponse.GetListItemChangesResult
     */
    @WebMethod(operationName = "GetListItemChanges", action = "http://schemas.microsoft.com/sharepoint/soap/GetListItemChanges")
    @WebResult(name = "GetListItemChangesResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListItemChanges", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListItemChanges")
    @ResponseWrapper(localName = "GetListItemChangesResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListItemChangesResponse")
    public com.microsoft.schemas.sharepoint.soap.GetListItemChangesResponse.GetListItemChangesResult getListItemChanges(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "viewFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.GetListItemChanges.ViewFields viewFields,
        @WebParam(name = "since", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String since,
        @WebParam(name = "contains", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.GetListItemChanges.Contains contains);

    /**
     * 
     * @param syncScope
     * @param contains
     * @param viewName
     * @param queryOptions
     * @param query
     * @param listName
     * @param rowLimit
     * @param viewFields
     * @param knowledge
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetListItemChangesWithKnowledgeResponse.GetListItemChangesWithKnowledgeResult
     */
    @WebMethod(operationName = "GetListItemChangesWithKnowledge", action = "http://schemas.microsoft.com/sharepoint/soap/GetListItemChangesWithKnowledge")
    @WebResult(name = "GetListItemChangesWithKnowledgeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListItemChangesWithKnowledge", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListItemChangesWithKnowledge")
    @ResponseWrapper(localName = "GetListItemChangesWithKnowledgeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListItemChangesWithKnowledgeResponse")
    public com.microsoft.schemas.sharepoint.soap.GetListItemChangesWithKnowledgeResponse.GetListItemChangesWithKnowledgeResult getListItemChangesWithKnowledge(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "viewName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String viewName,
        @WebParam(name = "query", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.GetListItemChangesWithKnowledge.Query query,
        @WebParam(name = "viewFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.GetListItemChangesWithKnowledge.ViewFields viewFields,
        @WebParam(name = "rowLimit", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String rowLimit,
        @WebParam(name = "queryOptions", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.GetListItemChangesWithKnowledge.QueryOptions queryOptions,
        @WebParam(name = "syncScope", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String syncScope,
        @WebParam(name = "knowledge", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.GetListItemChangesWithKnowledge.Knowledge knowledge,
        @WebParam(name = "contains", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.GetListItemChangesWithKnowledge.Contains contains);

    /**
     * 
     * @param contains
     * @param viewName
     * @param queryOptions
     * @param query
     * @param listName
     * @param rowLimit
     * @param viewFields
     * @param changeToken
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetListItemChangesSinceTokenResponse.GetListItemChangesSinceTokenResult
     */
    @WebMethod(operationName = "GetListItemChangesSinceToken", action = "http://schemas.microsoft.com/sharepoint/soap/GetListItemChangesSinceToken")
    @WebResult(name = "GetListItemChangesSinceTokenResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListItemChangesSinceToken", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListItemChangesSinceToken")
    @ResponseWrapper(localName = "GetListItemChangesSinceTokenResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListItemChangesSinceTokenResponse")
    public com.microsoft.schemas.sharepoint.soap.GetListItemChangesSinceTokenResponse.GetListItemChangesSinceTokenResult getListItemChangesSinceToken(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "viewName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String viewName,
        @WebParam(name = "query", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.GetListItemChangesSinceToken.Query query,
        @WebParam(name = "viewFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.GetListItemChangesSinceToken.ViewFields viewFields,
        @WebParam(name = "rowLimit", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String rowLimit,
        @WebParam(name = "queryOptions", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.GetListItemChangesSinceToken.QueryOptions queryOptions,
        @WebParam(name = "changeToken", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String changeToken,
        @WebParam(name = "contains", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.GetListItemChangesSinceToken.Contains contains);

    /**
     * 
     * @param listName
     * @param updates
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.UpdateListItemsResponse.UpdateListItemsResult
     */
    @WebMethod(operationName = "UpdateListItems", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateListItems")
    @WebResult(name = "UpdateListItemsResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UpdateListItems", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.UpdateListItems")
    @ResponseWrapper(localName = "UpdateListItemsResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.UpdateListItemsResponse")
    public com.microsoft.schemas.sharepoint.soap.UpdateListItemsResponse.UpdateListItemsResult updateListItems(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "updates", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.UpdateListItems.Updates updates);

    /**
     * 
     * @param syncScope
     * @param listName
     * @param updates
     * @param knowledge
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.UpdateListItemsWithKnowledgeResponse.UpdateListItemsWithKnowledgeResult
     */
    @WebMethod(operationName = "UpdateListItemsWithKnowledge", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateListItemsWithKnowledge")
    @WebResult(name = "UpdateListItemsWithKnowledgeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UpdateListItemsWithKnowledge", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.UpdateListItemsWithKnowledge")
    @ResponseWrapper(localName = "UpdateListItemsWithKnowledgeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.UpdateListItemsWithKnowledgeResponse")
    public com.microsoft.schemas.sharepoint.soap.UpdateListItemsWithKnowledgeResponse.UpdateListItemsWithKnowledgeResult updateListItemsWithKnowledge(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "updates", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.UpdateListItemsWithKnowledge.Updates updates,
        @WebParam(name = "syncScope", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String syncScope,
        @WebParam(name = "knowledge", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.UpdateListItemsWithKnowledge.Knowledge knowledge);

    /**
     * 
     * @param listName
     * @param message
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.AddDiscussionBoardItemResponse.AddDiscussionBoardItemResult
     */
    @WebMethod(operationName = "AddDiscussionBoardItem", action = "http://schemas.microsoft.com/sharepoint/soap/AddDiscussionBoardItem")
    @WebResult(name = "AddDiscussionBoardItemResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "AddDiscussionBoardItem", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.AddDiscussionBoardItem")
    @ResponseWrapper(localName = "AddDiscussionBoardItemResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.AddDiscussionBoardItemResponse")
    public com.microsoft.schemas.sharepoint.soap.AddDiscussionBoardItemResponse.AddDiscussionBoardItemResult addDiscussionBoardItem(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "message", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        byte[] message);

    /**
     * 
     * @param listRelPageUrl
     * @param strListName
     * @param wikiContent
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.AddWikiPageResponse.AddWikiPageResult
     */
    @WebMethod(operationName = "AddWikiPage", action = "http://schemas.microsoft.com/sharepoint/soap/AddWikiPage")
    @WebResult(name = "AddWikiPageResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "AddWikiPage", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.AddWikiPage")
    @ResponseWrapper(localName = "AddWikiPageResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.AddWikiPageResponse")
    public com.microsoft.schemas.sharepoint.soap.AddWikiPageResponse.AddWikiPageResult addWikiPage(
        @WebParam(name = "strListName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strListName,
        @WebParam(name = "listRelPageUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listRelPageUrl,
        @WebParam(name = "wikiContent", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String wikiContent);

    /**
     * 
     * @param strlistItemID
     * @param strlistID
     * @param strFieldName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetVersionCollectionResponse.GetVersionCollectionResult
     */
    @WebMethod(operationName = "GetVersionCollection", action = "http://schemas.microsoft.com/sharepoint/soap/GetVersionCollection")
    @WebResult(name = "GetVersionCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetVersionCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetVersionCollection")
    @ResponseWrapper(localName = "GetVersionCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetVersionCollectionResponse")
    public com.microsoft.schemas.sharepoint.soap.GetVersionCollectionResponse.GetVersionCollectionResult getVersionCollection(
        @WebParam(name = "strlistID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strlistID,
        @WebParam(name = "strlistItemID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strlistItemID,
        @WebParam(name = "strFieldName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strFieldName);

    /**
     * 
     * @param fileName
     * @param attachment
     * @param listItemID
     * @param listName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddAttachment", action = "http://schemas.microsoft.com/sharepoint/soap/AddAttachment")
    @WebResult(name = "AddAttachmentResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "AddAttachment", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.AddAttachment")
    @ResponseWrapper(localName = "AddAttachmentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.AddAttachmentResponse")
    public String addAttachment(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "listItemID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listItemID,
        @WebParam(name = "fileName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String fileName,
        @WebParam(name = "attachment", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        byte[] attachment);

    /**
     * 
     * @param listItemID
     * @param listName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetAttachmentCollectionResponse.GetAttachmentCollectionResult
     */
    @WebMethod(operationName = "GetAttachmentCollection", action = "http://schemas.microsoft.com/sharepoint/soap/GetAttachmentCollection")
    @WebResult(name = "GetAttachmentCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetAttachmentCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetAttachmentCollection")
    @ResponseWrapper(localName = "GetAttachmentCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetAttachmentCollectionResponse")
    public com.microsoft.schemas.sharepoint.soap.GetAttachmentCollectionResponse.GetAttachmentCollectionResult getAttachmentCollection(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "listItemID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listItemID);

    /**
     * 
     * @param listItemID
     * @param listName
     * @param url
     */
    @WebMethod(operationName = "DeleteAttachment", action = "http://schemas.microsoft.com/sharepoint/soap/DeleteAttachment")
    @RequestWrapper(localName = "DeleteAttachment", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.DeleteAttachment")
    @ResponseWrapper(localName = "DeleteAttachmentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.DeleteAttachmentResponse")
    public void deleteAttachment(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "listItemID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listItemID,
        @WebParam(name = "url", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String url);

    /**
     * 
     * @param checkoutToLocal
     * @param lastmodified
     * @param pageUrl
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CheckOutFile", action = "http://schemas.microsoft.com/sharepoint/soap/CheckOutFile")
    @WebResult(name = "CheckOutFileResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "CheckOutFile", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.CheckOutFile")
    @ResponseWrapper(localName = "CheckOutFileResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.CheckOutFileResponse")
    public boolean checkOutFile(
        @WebParam(name = "pageUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String pageUrl,
        @WebParam(name = "checkoutToLocal", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String checkoutToLocal,
        @WebParam(name = "lastmodified", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String lastmodified);

    /**
     * 
     * @param pageUrl
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "UndoCheckOut", action = "http://schemas.microsoft.com/sharepoint/soap/UndoCheckOut")
    @WebResult(name = "UndoCheckOutResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UndoCheckOut", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.UndoCheckOut")
    @ResponseWrapper(localName = "UndoCheckOutResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.UndoCheckOutResponse")
    public boolean undoCheckOut(
        @WebParam(name = "pageUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String pageUrl);

    /**
     * 
     * @param pageUrl
     * @param comment
     * @param checkinType
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CheckInFile", action = "http://schemas.microsoft.com/sharepoint/soap/CheckInFile")
    @WebResult(name = "CheckInFileResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "CheckInFile", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.CheckInFile")
    @ResponseWrapper(localName = "CheckInFileResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.CheckInFileResponse")
    public boolean checkInFile(
        @WebParam(name = "pageUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String pageUrl,
        @WebParam(name = "comment", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String comment,
        @WebParam(name = "CheckinType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String checkinType);

    /**
     * 
     * @param contentTypeId
     * @param listName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetListContentTypesResponse.GetListContentTypesResult
     */
    @WebMethod(operationName = "GetListContentTypes", action = "http://schemas.microsoft.com/sharepoint/soap/GetListContentTypes")
    @WebResult(name = "GetListContentTypesResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListContentTypes", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListContentTypes")
    @ResponseWrapper(localName = "GetListContentTypesResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListContentTypesResponse")
    public com.microsoft.schemas.sharepoint.soap.GetListContentTypesResponse.GetListContentTypesResult getListContentTypes(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId);

    /**
     * 
     * @param contentTypeId
     * @param propertyPrefix
     * @param listName
     * @param includeWebProperties
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetListContentTypesAndPropertiesResponse.GetListContentTypesAndPropertiesResult
     */
    @WebMethod(operationName = "GetListContentTypesAndProperties", action = "http://schemas.microsoft.com/sharepoint/soap/GetListContentTypesAndProperties")
    @WebResult(name = "GetListContentTypesAndPropertiesResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListContentTypesAndProperties", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListContentTypesAndProperties")
    @ResponseWrapper(localName = "GetListContentTypesAndPropertiesResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListContentTypesAndPropertiesResponse")
    public com.microsoft.schemas.sharepoint.soap.GetListContentTypesAndPropertiesResponse.GetListContentTypesAndPropertiesResult getListContentTypesAndProperties(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId,
        @WebParam(name = "propertyPrefix", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String propertyPrefix,
        @WebParam(name = "includeWebProperties", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        Boolean includeWebProperties);

    /**
     * 
     * @param contentTypeId
     * @param listName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetListContentTypeResponse.GetListContentTypeResult
     */
    @WebMethod(operationName = "GetListContentType", action = "http://schemas.microsoft.com/sharepoint/soap/GetListContentType")
    @WebResult(name = "GetListContentTypeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListContentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListContentType")
    @ResponseWrapper(localName = "GetListContentTypeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListContentTypeResponse")
    public com.microsoft.schemas.sharepoint.soap.GetListContentTypeResponse.GetListContentTypeResult getListContentType(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId);

    /**
     * 
     * @param contentTypeProperties
     * @param displayName
     * @param listName
     * @param fields
     * @param parentType
     * @param addToView
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateContentType", action = "http://schemas.microsoft.com/sharepoint/soap/CreateContentType")
    @WebResult(name = "CreateContentTypeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "CreateContentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.CreateContentType")
    @ResponseWrapper(localName = "CreateContentTypeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.CreateContentTypeResponse")
    public String createContentType(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "displayName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String displayName,
        @WebParam(name = "parentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String parentType,
        @WebParam(name = "fields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.CreateContentType.Fields fields,
        @WebParam(name = "contentTypeProperties", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.CreateContentType.ContentTypeProperties contentTypeProperties,
        @WebParam(name = "addToView", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String addToView);

    /**
     * 
     * @param contentTypeProperties
     * @param deleteFields
     * @param newFields
     * @param updateFields
     * @param contentTypeId
     * @param listName
     * @param addToView
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.UpdateContentTypeResponse.UpdateContentTypeResult
     */
    @WebMethod(operationName = "UpdateContentType", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateContentType")
    @WebResult(name = "UpdateContentTypeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UpdateContentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.UpdateContentType")
    @ResponseWrapper(localName = "UpdateContentTypeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.UpdateContentTypeResponse")
    public com.microsoft.schemas.sharepoint.soap.UpdateContentTypeResponse.UpdateContentTypeResult updateContentType(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId,
        @WebParam(name = "contentTypeProperties", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.UpdateContentType.ContentTypeProperties contentTypeProperties,
        @WebParam(name = "newFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.UpdateContentType.NewFields newFields,
        @WebParam(name = "updateFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.UpdateContentType.UpdateFields updateFields,
        @WebParam(name = "deleteFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.UpdateContentType.DeleteFields deleteFields,
        @WebParam(name = "addToView", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String addToView);

    /**
     * 
     * @param contentTypeId
     * @param listName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.DeleteContentTypeResponse.DeleteContentTypeResult
     */
    @WebMethod(operationName = "DeleteContentType", action = "http://schemas.microsoft.com/sharepoint/soap/DeleteContentType")
    @WebResult(name = "DeleteContentTypeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "DeleteContentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.DeleteContentType")
    @ResponseWrapper(localName = "DeleteContentTypeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.DeleteContentTypeResponse")
    public com.microsoft.schemas.sharepoint.soap.DeleteContentTypeResponse.DeleteContentTypeResult deleteContentType(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId);

    /**
     * 
     * @param contentTypeId
     * @param listName
     * @param newDocument
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.UpdateContentTypeXmlDocumentResponse.UpdateContentTypeXmlDocumentResult
     */
    @WebMethod(operationName = "UpdateContentTypeXmlDocument", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateContentTypeXmlDocument")
    @WebResult(name = "UpdateContentTypeXmlDocumentResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UpdateContentTypeXmlDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.UpdateContentTypeXmlDocument")
    @ResponseWrapper(localName = "UpdateContentTypeXmlDocumentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.UpdateContentTypeXmlDocumentResponse")
    public com.microsoft.schemas.sharepoint.soap.UpdateContentTypeXmlDocumentResponse.UpdateContentTypeXmlDocumentResult updateContentTypeXmlDocument(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId,
        @WebParam(name = "newDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.UpdateContentTypeXmlDocument.NewDocument newDocument);

    /**
     * 
     * @param listName
     * @param newDocument
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.UpdateContentTypesXmlDocumentResponse.UpdateContentTypesXmlDocumentResult
     */
    @WebMethod(operationName = "UpdateContentTypesXmlDocument", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateContentTypesXmlDocument")
    @WebResult(name = "UpdateContentTypesXmlDocumentResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UpdateContentTypesXmlDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.UpdateContentTypesXmlDocument")
    @ResponseWrapper(localName = "UpdateContentTypesXmlDocumentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.UpdateContentTypesXmlDocumentResponse")
    public com.microsoft.schemas.sharepoint.soap.UpdateContentTypesXmlDocumentResponse.UpdateContentTypesXmlDocumentResult updateContentTypesXmlDocument(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "newDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.soap.UpdateContentTypesXmlDocument.NewDocument newDocument);

    /**
     * 
     * @param documentUri
     * @param contentTypeId
     * @param listName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.DeleteContentTypeXmlDocumentResponse.DeleteContentTypeXmlDocumentResult
     */
    @WebMethod(operationName = "DeleteContentTypeXmlDocument", action = "http://schemas.microsoft.com/sharepoint/soap/DeleteContentTypeXmlDocument")
    @WebResult(name = "DeleteContentTypeXmlDocumentResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "DeleteContentTypeXmlDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.DeleteContentTypeXmlDocument")
    @ResponseWrapper(localName = "DeleteContentTypeXmlDocumentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.DeleteContentTypeXmlDocumentResponse")
    public com.microsoft.schemas.sharepoint.soap.DeleteContentTypeXmlDocumentResponse.DeleteContentTypeXmlDocumentResult deleteContentTypeXmlDocument(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId,
        @WebParam(name = "documentUri", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String documentUri);

    /**
     * 
     * @param webUrl
     * @param contentTypeId
     * @param listName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.ApplyContentTypeToListResponse.ApplyContentTypeToListResult
     */
    @WebMethod(operationName = "ApplyContentTypeToList", action = "http://schemas.microsoft.com/sharepoint/soap/ApplyContentTypeToList")
    @WebResult(name = "ApplyContentTypeToListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "ApplyContentTypeToList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.ApplyContentTypeToList")
    @ResponseWrapper(localName = "ApplyContentTypeToListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.ApplyContentTypeToListResponse")
    public com.microsoft.schemas.sharepoint.soap.ApplyContentTypeToListResponse.ApplyContentTypeToListResult applyContentTypeToList(
        @WebParam(name = "webUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String webUrl,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId,
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName);

}
