# mmp_splunk

FROM alpine:3.3

MAINTAINER Marcus Portmann "http://mmp.guru"

# Install dependencies 
#RUN apk --update add curl ca-certificates tar sqlite icu bash && \
#    curl -Ls https://circle-artifacts.com/gh/andyshinn/alpine-pkg-glibc/6/artifacts/0/home/ubuntu/alpine-pkg-glibc/packages/x86_64/glibc-2.21-r2.apk > /tmp/glibc-2.21-r2.apk && \
#    apk add --allow-untrusted /tmp/glibc-2.21-r2.apk


# RUN curl -o /tmp/wildfly-10.0.0.Final.tar.gz \
#  http://download.jboss.org/wildfly/10.0.0.Final/wildfly-10.0.0.Final.tar.gz \
#  && tar zxf /tmp/wildfly-10.0.0.Final.tar.gz -C /opt \





