
package com.rsa.names._2009._12.product.riat.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "STSService", targetNamespace = "http://www.rsa.com/names/2009/12/product/riat/wsdl", wsdlLocation = "file:/Volumes/Data/Develop/Projects/mmp-java/src/mmp-vmware/src/main/resources/META-INF/wsdl/STSService.wsdl")
public class STSService
    extends Service
{

    private final static URL STSSERVICE_WSDL_LOCATION;
    private final static WebServiceException STSSERVICE_EXCEPTION;
    private final static QName STSSERVICE_QNAME = new QName("http://www.rsa.com/names/2009/12/product/riat/wsdl", "STSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Volumes/Data/Develop/Projects/mmp-java/src/mmp-vmware/src/main/resources/META-INF/wsdl/STSService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STSSERVICE_WSDL_LOCATION = url;
        STSSERVICE_EXCEPTION = e;
    }

    public STSService() {
        super(__getWsdlLocation(), STSSERVICE_QNAME);
    }

    public STSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STSSERVICE_QNAME, features);
    }

    public STSService(URL wsdlLocation) {
        super(wsdlLocation, STSSERVICE_QNAME);
    }

    public STSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STSSERVICE_QNAME, features);
    }

    public STSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public STSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns STSServicePortType
     */
    @WebEndpoint(name = "STSService_Port")
    public STSServicePortType getSTSServicePort() {
        return super.getPort(new QName("http://www.rsa.com/names/2009/12/product/riat/wsdl", "STSService_Port"), STSServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns STSServicePortType
     */
    @WebEndpoint(name = "STSService_Port")
    public STSServicePortType getSTSServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.rsa.com/names/2009/12/product/riat/wsdl", "STSService_Port"), STSServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STSSERVICE_EXCEPTION!= null) {
            throw STSSERVICE_EXCEPTION;
        }
        return STSSERVICE_WSDL_LOCATION;
    }

}
