package guru.mmp.service.codes.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-02T21:08:49.190+02:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "CodesService", 
                  wsdlLocation = "file:/Users/marcus/Develop/MMP/mmp-java/src/mmp-application/src/main/resources/META-INF/wsdl/CodesService.wsdl",
                  targetNamespace = "http://ws.codes.service.mmp.guru") 
public class CodesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.codes.service.mmp.guru", "CodesService");
    public final static QName CodesService = new QName("http://ws.codes.service.mmp.guru", "CodesService");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/marcus/Develop/MMP/mmp-java/src/mmp-application/src/main/resources/META-INF/wsdl/CodesService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CodesService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/marcus/Develop/MMP/mmp-java/src/mmp-application/src/main/resources/META-INF/wsdl/CodesService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CodesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CodesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CodesService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CodesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CodesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CodesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ICodesService
     */
    @WebEndpoint(name = "CodesService")
    public ICodesService getCodesService() {
        return super.getPort(CodesService, ICodesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICodesService
     */
    @WebEndpoint(name = "CodesService")
    public ICodesService getCodesService(WebServiceFeature... features) {
        return super.getPort(CodesService, ICodesService.class, features);
    }

}
