package guru.mmp.service.codes.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * The Codes service.
 *
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-02T20:50:57.582+02:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://ws.codes.service.mmp.guru", name = "ICodesService")
@XmlSeeAlso({ObjectFactory.class})
public interface ICodesService {

    @WebMethod(operationName = "GetCodeCategoryWithParameters", action = "http://ws.codes.service.mmp.guru/ICodesService/GetCodeCategoryWithParameters")
    @RequestWrapper(localName = "GetCodeCategoryWithParameters", targetNamespace = "http://ws.codes.service.mmp.guru", className = "guru.mmp.service.codes.ws.GetCodeCategoryWithParameters")
    @ResponseWrapper(localName = "GetCodeCategoryWithParametersResponse", targetNamespace = "http://ws.codes.service.mmp.guru", className = "guru.mmp.service.codes.ws.GetCodeCategoryWithParametersResponse")
    @WebResult(name = "out", targetNamespace = "http://ws.codes.service.mmp.guru")
    public guru.mmp.service.codes.ws.CodeCategory getCodeCategoryWithParameters(
        @WebParam(name = "Id", targetNamespace = "http://ws.codes.service.mmp.guru")
        java.lang.String id,
        @WebParam(name = "Parameters", targetNamespace = "http://ws.codes.service.mmp.guru")
        java.util.List<guru.mmp.service.codes.ws.Parameter> parameters,
        @WebParam(name = "LastRetrieved", targetNamespace = "http://ws.codes.service.mmp.guru")
        java.time.LocalDateTime lastRetrieved,
        @WebParam(name = "ReturnCodesIfCurrent", targetNamespace = "http://ws.codes.service.mmp.guru")
        boolean returnCodesIfCurrent
    ) throws CodesServiceFault;

    @WebMethod(operationName = "GetVersion", action = "http://ws.codes.service.mmp.guru/ICodesService/GetVersion")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "http://ws.codes.service.mmp.guru", className = "guru.mmp.service.codes.ws.GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "http://ws.codes.service.mmp.guru", className = "guru.mmp.service.codes.ws.GetVersionResponse")
    @WebResult(name = "out", targetNamespace = "http://ws.codes.service.mmp.guru")
    public java.lang.String getVersion() throws CodesServiceFault;

    @WebMethod(operationName = "GetCodeCategory", action = "http://ws.codes.service.mmp.guru/ICodesService/GetCodeCategory")
    @RequestWrapper(localName = "GetCodeCategory", targetNamespace = "http://ws.codes.service.mmp.guru", className = "guru.mmp.service.codes.ws.GetCodeCategory")
    @ResponseWrapper(localName = "GetCodeCategoryResponse", targetNamespace = "http://ws.codes.service.mmp.guru", className = "guru.mmp.service.codes.ws.GetCodeCategoryResponse")
    @WebResult(name = "out", targetNamespace = "http://ws.codes.service.mmp.guru")
    public guru.mmp.service.codes.ws.CodeCategory getCodeCategory(
        @WebParam(name = "Id", targetNamespace = "http://ws.codes.service.mmp.guru")
        java.lang.String id,
        @WebParam(name = "LastRetrieved", targetNamespace = "http://ws.codes.service.mmp.guru")
        java.time.LocalDateTime lastRetrieved,
        @WebParam(name = "ReturnCodesIfCurrent", targetNamespace = "http://ws.codes.service.mmp.guru")
        boolean returnCodesIfCurrent
    ) throws CodesServiceFault;
}
