
package guru.mmp.service.codes.ws;

//~--- JDK imports ------------------------------------------------------------

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.Calendar;
import java.util.List;

/**
 * The Codes service.
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "ICodesService", targetNamespace = "http://ws.codes.service.mmp.guru")
@XmlSeeAlso({ ObjectFactory.class })
public interface ICodesService
{
  /**
   *
   * @param id
   * @param lastRetrieved
   * @param returnCodesIfCurrent
   * @return
   *     returns guru.mmp.service.codes.ws.CodeCategory
   * @throws CodesServiceFault
   */
  @WebMethod(operationName = "GetCodeCategory",
      action = "http://ws.codes.service.mmp.guru/ICodesService/GetCodeCategory")
  @WebResult(name = "out", targetNamespace = "http://ws.codes.service.mmp.guru")
  @RequestWrapper(localName = "GetCodeCategory",
      targetNamespace = "http://ws.codes.service.mmp.guru",
      className = "guru.mmp.service.codes.ws.GetCodeCategory")
  @ResponseWrapper(localName = "GetCodeCategoryResponse",
      targetNamespace = "http://ws.codes.service.mmp.guru",
      className = "guru.mmp.service.codes.ws.GetCodeCategoryResponse")
  public CodeCategory getCodeCategory(@WebParam(name = "id",
      targetNamespace = "http://ws.codes.service.mmp.guru") String id, @WebParam(
          name = "lastRetrieved",
              targetNamespace = "http://ws.codes.service.mmp.guru") Calendar lastRetrieved,
                  @WebParam(name = "returnCodesIfCurrent",
                      targetNamespace = "http://ws.codes.service.mmp.guru") boolean returnCodesIfCurrent)
    throws CodesServiceFault
  ;

  /**
   *
   * @param id
   * @param lastRetrieved
   * @param parameters
   * @param returnCodesIfCurrent
   * @return
   *     returns guru.mmp.service.codes.ws.CodeCategory
   * @throws CodesServiceFault
   */
  @WebMethod(operationName = "GetCodeCategoryWithParameters",
      action = "http://ws.codes.service.mmp.guru/ICodesService/GetCodeCategoryWithParameters")
  @WebResult(name = "out", targetNamespace = "http://ws.codes.service.mmp.guru")
  @RequestWrapper(localName = "GetCodeCategoryWithParameters",
      targetNamespace = "http://ws.codes.service.mmp.guru",
      className = "guru.mmp.service.codes.ws.GetCodeCategoryWithParameters")
  @ResponseWrapper(localName = "GetCodeCategoryWithParametersResponse",
      targetNamespace = "http://ws.codes.service.mmp.guru",
      className = "guru.mmp.service.codes.ws.GetCodeCategoryWithParametersResponse")
  public CodeCategory getCodeCategoryWithParameters(@WebParam(name = "id",
      targetNamespace = "http://ws.codes.service.mmp.guru") String id, @WebParam(
          name = "parameters",
              targetNamespace = "http://ws.codes.service.mmp.guru") List<Parameter> parameters,
                  @WebParam(name = "lastRetrieved",
                      targetNamespace = "http://ws.codes.service.mmp.guru") Calendar lastRetrieved,
                          @WebParam(name = "returnCodesIfCurrent",
                              targetNamespace = "http://ws.codes.service.mmp.guru") boolean returnCodesIfCurrent)
    throws CodesServiceFault
  ;

  /**
   *
   * @return
   *     returns java.lang.String
   * @throws CodesServiceFault
   */
  @WebMethod(operationName = "GetVersion",
      action = "http://ws.codes.service.mmp.guru/ICodesService/GetVersion")
  @WebResult(name = "out", targetNamespace = "http://ws.codes.service.mmp.guru")
  @RequestWrapper(localName = "GetVersion", targetNamespace = "http://ws.codes.service.mmp.guru",
      className = "guru.mmp.service.codes.ws.GetVersion")
  @ResponseWrapper(localName = "GetVersionResponse",
      targetNamespace = "http://ws.codes.service.mmp.guru",
      className = "guru.mmp.service.codes.ws.GetVersionResponse")
  public String getVersion()
    throws CodesServiceFault
  ;
}
